// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
// import { defineConfig } from "prisma/config"; // Not needed in modern Prisma setup

// Note: Modern Prisma with Next.js doesn't require this config file
// Configuration is handled via prisma/schema.prisma and environment variables
